### ISSUE TITLE
I can't truncate output from quill-view-html

### ISSUE THREAD

**Issue by danielemonaca** [KillerCodeMonkey/ngx-quill#1018]
I need some help with this: 

**I have this CSS class:** 

```CSS
.multi-line-truncate {
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3;
  overflow: hidden;
  text-overflow: ellipsis;
  max-width: 200px;
}
```

**This is the result I get with this code:**

```HTML
        <td>
          <p class="multi-line-truncate">Just trying some text and that is what it looks like. When I add too much text,
            it should break and at the end insert simple ellipsis.</p>
        </td>
```

**Result:**

<img width="331" alt="working" src="https://user-images.githubusercontent.com/47630631/91861235-df961700-ec6c-11ea-9dee-17409f75a19a.png">

**Here is when I try with quill-view-html:**

```HTML
        <td>
          <p class="multi-line-truncate">
            <quill-view-html [content]="formGroup.get('description').value"
                             theme="snow"></quill-view-html>
          </p>
        </td>
```

**Result:**

<img width="338" alt="broken" src="https://user-images.githubusercontent.com/47630631/91862151-e2ddd280-ec6d-11ea-8d2f-ffda6221b0ac.png">
