### ISSUE TITLE
Custom font sizes problem

### ISSUE THREAD

**Issue by djfishe** [KillerCodeMonkey/ngx-quill#181]
Hi,
I'm trying to add custom font sizes to the editor by using `customOptions` but somehow the editor doesn't show the proper labels and the inline style is not applied.
Here is my config (modules and customOptions) from the component.ts:
```javascript
this.customOptions = [{
    import: 'attributors/style/size',
    whitelist: ['10', '16', '22', '36', '48', '72', '144']
}];

this.quillModules = {
    toolbar: [
        [{ 'size': [false, '10', '16', '22', '36', '48', '72', '144'] }],
        ['bold', 'italic', 'underline', 'strike'],
        [{ 'color': [] }, { 'background': [] }],
        [{ 'align': [false, 'center', 'right', 'justify'] }],
        [{ 'indent': '-1' }, { 'indent': '+1' }],
        [{ 'list': 'ordered' }, { 'list': 'bullet' }],
    ]
};
```

The view - component.html:
```html
<quill-editor *ngIf="isInEditMode" 
    [(ngModel)]="content" 
    [modules]="quillModules"
    [customOptions]="customOptions"
    (onEditorCreated)="setFocus($event)">
</quill-editor>
``` 

How it is manifested:
![screen shot 2018-05-17 at 15 45 50](https://user-images.githubusercontent.com/3807749/40182523-e65f874e-59eb-11e8-835c-4eb0004c7754.png)

What is generated (from the dev tools):
![screen shot 2018-05-17 at 16 04 36](https://user-images.githubusercontent.com/3807749/40182612-11dbacfe-59ec-11e8-9371-5c8178dac1d9.png)

Can you take a look and possibly guide to right direction? Maybe I'm missing something.

Thank you.

**Comment by KillerCodeMonkey** [comment]
i think you need to create a custom toolbar with the correct labels and values.

**Comment by djfishe** [comment]
Yeah this works!
I would like to add that, in order to see the current selection in the dropdown you need to add additional selectors, like this:
```css
.ql-snow .ql-picker.ql-size .ql-picker-item[data-value="10px"]::before,
.ql-snow .ql-picker.ql-size .ql-picker-label.ql-active[data-value="10px"]::before {
    content: '10px';
}

.ql-snow .ql-picker.ql-size .ql-picker-item[data-value="16px"]::before,
.ql-snow .ql-picker.ql-size .ql-picker-label.ql-active[data-value="16px"]::before {
    content: '16px';
}

.ql-snow .ql-picker.ql-size .ql-picker-item[data-value="22px"]::before,
.ql-snow .ql-picker.ql-size .ql-picker-label.ql-active[data-value="22px"]::before {
    content: '22px';
}
```
Thank you!
