### ISSUE TITLE
I can't change the color of the toolbar buttons with CSS

### ISSUE THREAD

**Issue by xdvi** [KillerCodeMonkey/ngx-quill#1944]
I've tried these methods and a few more, but I can't get it to work

.ql-toolbar.ql-snow {
 color: white
}

![{0F90D07A-A5CD-4D9C-B52C-BABA34C5172F}](https://github.com/user-attachments/assets/980c1261-3353-4ee8-a712-f18088f2ef86)

**Comment by KillerCodeMonkey** [comment]
for the placeholder of the editor
```CSS
:host ::ng-deep .ql-editor.ql-blank::before {
  content: attr(data-placeholder);
  color: red !important;
}
```

Toolbar icons
```CSS
:host ::ng-deep .ql-stroke,
:host ::ng-deep .ql-snow .ql-fill,
:host ::ng-deep .ql-snow .ql-picker-label,
:host ::ng-deep .ql-snow .ql-picker-item {
  color: red !important;
  fill: red !important;
  stroke: red !important;
}
```
